let DB=null,current=null,studentToken='',timer=null;
const $=id=>document.getElementById(id); const money=n=>'₹'+Number(n||0).toLocaleString('en-IN');
async function api(url,opt={}){opt.headers={...(opt.headers||{}),...(studentToken?{'x-student-token':studentToken}:{})};const r=await fetch(url,opt);let j={};try{j=await r.json()}catch{}if(!r.ok)throw Error(j.error||'Something went wrong');return j}
async function loadPublic(){const r=await fetch('/api/public-state',{cache:'no-store'});const j=await r.json();DB=j&&typeof j==='object'?j:{};DB.settings=(DB.settings&&typeof DB.settings==='object')?DB.settings:{};DB.courses=Array.isArray(DB.courses)?DB.courses:[];DB.posts=Array.isArray(DB.posts)?DB.posts:[];DB.announcements=Array.isArray(DB.announcements)?DB.announcements:[];checkWebsiteUpdate();}
async function loadStudent(){const j=await api('/api/student-state');DB={...DB,...j};DB.settings=(DB.settings&&typeof DB.settings==='object')?DB.settings:{};for(const k of ['courses','materials','assignments','submissions','liveClasses','announcements','posts','notifications','receipts','doubts','comments'])if(!Array.isArray(DB[k]))DB[k]=[];current=j&&j.user?j.user:{};current.enrollments=Array.isArray(current.enrollments)?current.enrollments:[];current.purchased=Array.isArray(current.purchased)?current.purchased:[];current.progress=(current.progress&&typeof current.progress==='object')?current.progress:{};current.completedLessons=(current.completedLessons&&typeof current.completedLessons==='object')?current.completedLessons:{};localStorage.setItem('hsa_user',JSON.stringify(current));renderHeader();}
function applyBranding(){const logo=DB?.settings?.logo||'/academy-logo.png';for(const id of ['brandMark','loginBrandMark']){const e=$(id);if(e){e.innerHTML=`<img src="${logo}" alt="Academy logo">`;e.classList.add('logo-mark');}}}
function renderHeader(){applyBranding();if(!current)return;$('ownerPanel')?.classList.toggle('hidden',current.role!=='superadmin');const name=current.name||'Student';const userName=$('userName');if(userName)userName.textContent=name;const avatar=$('topAvatar');if(avatar)avatar.textContent=name.split(' ').map(x=>x[0]).slice(0,2).join('').toUpperCase();const dot=$('notifDot');if(dot)dot.style.display=(DB.notifications||[]).some(n=>!(Array.isArray(n.readBy)&&n.readBy.includes(current.id))&&!n.read)?'block':'none';}
function toast(t){const e=$('toast');if(!e)return;e.className='toast';e.textContent=t;setTimeout(()=>e.className='',3200)}
function openModal(html){$('modalBody').innerHTML=html;$('modal').classList.remove('hidden')}function closeModal(){clearInterval(timer);$('modal').classList.add('hidden')}
function openLoginPanel(){try{sessionStorage.setItem('hsa_login_open','1');history.replaceState(null,'','#login')}catch{}document.getElementById('loginOverlay')?.classList.remove('hidden');document.body.classList.add('login-open');hideLastStudentSuggestion();setTimeout(()=>document.getElementById('studentEmail')?.focus(),100)}
function hideLastStudentSuggestion(){const box=$('lastStudentSuggestion');if(box){box.innerHTML='';box.classList.add('hidden')}}
function checkStudentEmailSuggestion(){const email=String($('studentEmail')?.value||'').trim().toLowerCase();const savedEmail=String(localStorage.getItem('hsa_last_student_email')||'').trim().toLowerCase();const name=localStorage.getItem('hsa_last_student_name');const remember=localStorage.getItem('hsa_student_remember_token');const box=$('lastStudentSuggestion');if(!box)return;if(email&&savedEmail===email&&name&&remember){box.innerHTML=`<button type="button" class="outline suggestion-btn" onclick="useLastStudent()">Continue as <b>${String(name).replace(/[&<>]/g,'')}</b> · ${String(email).replace(/[&<>]/g,'')}</button>`;box.classList.remove('hidden');if($('studentName')&&!$('studentName').value)$('studentName').value=name}else hideLastStudentSuggestion()}
function closeLoginPanel(e){if(e&&e.target!==e.currentTarget)return;try{sessionStorage.removeItem('hsa_login_open');if(location.hash==='#login')history.replaceState(null,'',location.pathname+location.search)}catch{}document.getElementById('loginOverlay')?.classList.add('hidden');document.body.classList.remove('login-open')}
function scrollToTop(){window.scrollTo({top:0,behavior:'smooth'})}
function showLastStudentSuggestion(){const n=localStorage.getItem('hsa_last_student_name'),em=localStorage.getItem('hsa_last_student_email');const box=$('lastStudentSuggestion');if(box&&n&&em){box.innerHTML=`<button type="button" class="outline suggestion-btn" onclick="useLastStudent()">Continue as <b>${String(n).replace(/[&<>]/g,'')}</b> · ${String(em).replace(/[&<>]/g,'')}</button>`;box.classList.remove('hidden')}}
async function useLastStudent(){const n=localStorage.getItem('hsa_last_student_name'),em=localStorage.getItem('hsa_last_student_email'),remember=localStorage.getItem('hsa_student_remember_token');if(!n||!em)return;if(remember){try{const r=await fetch('/api/auth/remember-login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:em,rememberToken:remember})});const j=await r.json();if(r.ok&&j.token){studentToken=j.token;localStorage.setItem('hsa_student_token',j.token);localStorage.setItem('hsa_last_student_id',j.user.id);current=j.user;await loadPublic();await loadStudent();$('loginOverlay').classList.add('hidden');document.body.classList.remove('login-open');$('publicHome').classList.add('hidden');$('app').classList.remove('hidden');go('home');return;}}catch(e){}}$('studentName').value=n;$('studentEmail').value=em;$('nameForm').requestSubmit();}
function backToName(){$('studentOtpForm').classList.add('hidden');$('nameForm').classList.remove('hidden');$('studentOtp').value='';$('otpHint').textContent=''}
async function sendStudentOtp(e){e.preventDefault();const name=$('studentName').value.trim(),email=$('studentEmail').value.trim();if(!name||!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)){toast('Please enter your full name and a valid email.');return}try{const rememberedEmail=localStorage.getItem('hsa_last_student_email'),remember=localStorage.getItem('hsa_student_remember_token');if(remember&&rememberedEmail===email){const rr=await fetch('/api/auth/remember-login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email,rememberToken:remember})});const jj=await rr.json();if(rr.ok&&jj.token){studentToken=jj.token;localStorage.setItem('hsa_student_token',jj.token);localStorage.setItem('hsa_last_student_name',jj.user.name);localStorage.setItem('hsa_last_student_id',jj.user.id);current=jj.user;await loadPublic();await loadStudent();$('loginOverlay').classList.add('hidden');document.body.classList.remove('login-open');$('publicHome').classList.add('hidden');$('app').classList.remove('hidden');go('home');return;}}const r=await fetch('/api/auth/request-otp',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name,email})});const j=await r.json();if(!r.ok)throw Error(j.error||'Unable to send OTP');$('studentId').value=j.studentId;$('studentIdDisplay').textContent=j.studentId;$('studentEmailHidden').value=email;$('nameForm').classList.add('hidden');$('studentOtpForm').classList.remove('hidden');$('otpHint').textContent=`OTP sent to ${email}. It expires in 10 minutes.`;$('studentOtp').focus();toast('OTP sent to your email.')}catch(err){toast(err.message)}}
async function verifyStudentOtp(e){e.preventDefault();const otp=$('studentOtp').value.trim();if(!/^\d{4,6}$/.test(otp)){toast('Enter the OTP sent to your email.');return}try{const r=await fetch('/api/auth/verify-otp',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({studentId:$('studentId').value,email:$('studentEmailHidden').value,otp})});const j=await r.json();if(!r.ok)throw Error(j.error||'Invalid OTP');studentToken=j.token;localStorage.setItem('hsa_student_token',studentToken);localStorage.setItem('hsa_student_remember_token',j.rememberToken||'');localStorage.setItem('hsa_last_student_name',j.user.name);localStorage.setItem('hsa_last_student_email',j.user.email||$('studentEmailHidden').value);localStorage.setItem('hsa_last_student_id',j.user.id);current=j.user;await loadPublic();await loadStudent();$('loginOverlay').classList.add('hidden');document.body.classList.remove('login-open');$('publicHome').classList.add('hidden');$('app').classList.remove('hidden');go('home')}catch(err){toast(err.message)}}
async function adminQuickLogin(e){e.preventDefault();try{const r=await fetch('/api/admin/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({password:$('quickAdminPassword').value})});const j=await r.json();if(!r.ok)throw Error(j.error||'Admin password is incorrect');localStorage.setItem('hsa_admin_token',j.token);location.href='/admin.html'}catch(err){toast(err.message)}}
function checkWebsiteUpdate(){const version=String(DB?.settings?.siteVersion||'1');const old=localStorage.getItem('hsa_site_version');if(old&&old!==version)showUpdateBanner(version);localStorage.setItem('hsa_site_version',version)}
function showUpdateBanner(version){if(document.getElementById('siteUpdateBanner'))return;const b=document.createElement('div');b.id='siteUpdateBanner';b.className='site-update-banner';b.innerHTML=`<span><b>Update your website</b><small>A newer version of Hafiz Shahid's Academy is available.</small></span><button class="primary" onclick="updateWebsite()">Update Now</button><button class="update-close" onclick="this.parentElement.remove()">×</button>`;document.body.appendChild(b)}
async function updateWebsite(){try{await fetch('/api/public-state?refresh='+Date.now(),{cache:'no-store'});}finally{location.reload();}}
$('nameForm')?.addEventListener('submit',sendStudentOtp);$('studentOtpForm')?.addEventListener('submit',verifyStudentOtp);$('studentEmail')?.addEventListener('input',checkStudentEmailSuggestion);$('studentEmail')?.addEventListener('blur',checkStudentEmailSuggestion);

// ---------------- Student dashboard navigation helpers ----------------
function course(id){ return (DB?.courses||[]).find(c=>String(c.id)===String(id)); }
function enrollment(courseId){
  return (current?.enrollments||[]).find(e=>String(e.courseId)===String(courseId));
}
function active(courseId){
  if(!course(courseId)) return false;
  if(current?.role==='superadmin') return true;
  const special=String(current?.name||'').toLowerCase().replace(/[^a-z0-9]/g,'')==='hafizshahid';
  if(special) return true;
  const e=enrollment(courseId);
  if(e && e.status==='active' && new Date(e.endDate)>=new Date()) return true;
  return Array.isArray(current?.purchased) && current.purchased.map(String).includes(String(courseId));
}
function progress(courseId){
  const value=Number((current?.progress||{})[courseId]||0);
  return Math.max(0,Math.min(100,value));
}
function go(page){
  if(!current){ return; }
  const routes={home:renderHome,courses:renderCourses,purchased:renderPurchased,materials:renderMaterials,downloads:renderDownloads,assignments:renderAssignments,live:renderLive,certificates:renderCertificates,profile:renderProfile,settings:renderSettings,notifications:renderNotifications,doubts:renderDoubts,search:renderGlobalSearch};
  const render=routes[page]||renderHome;
  try{sessionStorage.setItem('hsa_student_page',page);if(page!=='course'){sessionStorage.removeItem('hsa_course_id');sessionStorage.removeItem('hsa_lesson_id')}}catch{}
  let result;
  try{result=render();}catch(err){console.error('Student page render error:',err);const content=$('content');if(content)content.innerHTML='<div class="card page-error"><h2>Student dashboard could not load this section.</h2><p>Please refresh the page. Your account and saved data are safe.</p><button class="primary" onclick="location.reload()">Refresh Dashboard</button></div>';return;}
  document.querySelectorAll('[data-nav]').forEach(btn=>{
    btn.classList.toggle('active',btn.dataset.nav===page);
  });
  document.getElementById('sidebar')?.classList.remove('open');
  return result;
}
function toggleSidebar(){
  document.getElementById('sidebar')?.classList.toggle('open');
}
function logout(){
  studentToken='';
  current=null;
  localStorage.removeItem('hsa_student_token');
  localStorage.removeItem('hsa_user');
  document.getElementById('app')?.classList.add('hidden');
  document.getElementById('publicHome')?.classList.remove('hidden');
  document.getElementById('loginOverlay')?.classList.add('hidden');
  document.body.classList.remove('login-open');
  document.getElementById('nameForm')?.classList.remove('hidden');
  document.getElementById('studentOtpForm')?.classList.add('hidden');
  if(document.getElementById('studentOtp')) document.getElementById('studentOtp').value='';
  document.getElementById('studentName')?.focus();
}

function startLatestPostsSlider(){
  const el=document.getElementById('latestPostsSlider');
  if(!el || el.dataset.autoSlide==='1' || el.children.length<2) return;
  el.dataset.autoSlide='1';
  let timer=setInterval(()=>{
    if(!document.body.contains(el)){clearInterval(timer);return;}
    const card=el.querySelector('.latest-post-card');
    if(!card)return;
    const step=card.getBoundingClientRect().width+12;
    const atEnd=el.scrollLeft+el.clientWidth>=el.scrollWidth-8;
    el.scrollTo({left:atEnd?0:el.scrollLeft+step,behavior:'smooth'});
  },3500);
  el.addEventListener('mouseenter',()=>clearInterval(timer));
  el.addEventListener('touchstart',()=>clearInterval(timer),{passive:true});
}
function latestPostCard(p){return `<article class="latest-post-card"><img src="${p.image||'/shahid.jpg'}" alt="Post"><div class="latest-post-card-body"><b>${p.title||''}</b><p>${p.text||''}</p><small>${new Date(p.createdAt).toLocaleDateString('en-IN')}</small></div></article>`;}
function renderHome(){
  const posts=Array.isArray(DB?.posts)?DB.posts:[];
  const mine=(Array.isArray(current?.enrollments)?current.enrollments:[]).filter(e=>e&&e.status==='active');
  const settings=DB?.settings&&typeof DB.settings==='object'?DB.settings:{};
  const postHtml=posts.slice(0,6).map(latestPostCard).join('')||'<div class="empty">No posts yet.</div>';
  $('content').innerHTML=`<section class="hero reveal"><div class="hero-copy"><div class="eyebrow">HAFIZ SHAHID'S ACADEMY</div><h1>Learn today.<br><span>Grow for life.</span></h1><p>Recorded classes, live Zoom sessions, assignments, study material and certificates — built around your learning journey.</p><div class="row"><button class="primary" onclick="go('courses')">Explore Courses →</button><button class="outline" onclick="go('purchased')">My Learning</button></div><div class="hero-pills"><span>✓ Student ID Login</span><span>✓ Verified Payments</span><span>✓ 80% Certificate</span></div></div><div class="hero-photo" style="background-image:url('${settings.heroImage||'/shahid.jpg'}')"><div class="photo-tag">Hafiz Shahid<br><small>Founder & Educator</small></div></div></section>
  <div class="feature-strip"><button type="button" onclick="go('purchased')">🎥<b>Recorded Classes</b><span>Open your recorded lessons</span></button><button type="button" onclick="go('live')">📹<b>Live Classes</b><span>Open scheduled Zoom classes</span></button><button type="button" onclick="go('assignments')">📝<b>Assignments</b><span>Open and submit assignments</span></button><button type="button" onclick="go('certificates')">🏆<b>Certificates</b><span>Open your certificates</span></button></div>
  <div class="page-head"><div><div class="eyebrow">YOUR JOURNEY</div><h1>Welcome, ${current.name||'Student'}</h1><p>Your active courses and latest academy updates.</p></div><button class="outline" onclick="go('notifications')">Notifications</button></div>
  <section class="card dashboard-section purchased-dashboard-section"><div class="section-title-row"><div><h3>Purchased Courses</h3><p class="small">Your active courses</p></div></div><div class="purchased-square-grid">${mine.length?mine.map(e=>learningCard(e)).join(''):'<div class="empty">No purchased courses yet.<br><button class="primary" style="margin-top:12px" onclick="go(\'courses\')">Find a Course</button></div>'}</div></section>
  <section class="card dashboard-section latest-posts-dashboard-section"><div class="latest-posts-head"><div><h3>Latest Posts</h3><p class="small">Swipe or slide to see the latest updates</p></div><span class="latest-posts-hint">Swipe / slide</span></div><div class="latest-posts-slider" id="latestPostsSlider">${postHtml}</div></section>`;
  startLatestPostsSlider();
}
function learningCard(e){const c=course(e.courseId),pct=progress(e.courseId),done=(current?.completedLessons?.[e.courseId]||[]).length,total=(c?.lessons||[]).length;return `<article class="learning-card"><div class="thumb" style="background-image:url('${c?.image||'/shahid.jpg'}')"></div><div class="learning-card-body"><span class="badge">${c?.category||'Course'}</span><h3>${c?.title||e.courseTitle}</h3><div class="small">Access until ${new Date(e.endDate).toLocaleDateString('en-IN')}</div><div class="progress" style="margin-top:10px"><i style="width:${pct}%"></i></div><div class="small progress-meta" style="margin-top:5px">${pct}% complete${total?` • ${Math.min(done,total)}/${total} lessons`:''}</div><button type="button" class="primary wide" data-open-course="${esc(e.courseId)}">Continue Learning</button></div></article>`}
function renderPurchased(){const arr=(Array.isArray(current?.enrollments)?current.enrollments:[]).filter(e=>e&&e.status==='active');$('content').innerHTML=`<div class="page-head"><div><div class="eyebrow">MY LEARNING</div><h1>Purchased Courses</h1><p>Continue learning from your active courses.</p></div></div><section class="card dashboard-section purchased-dashboard-section"><div class="purchased-square-grid">${arr.length?arr.map(learningCard).join(''):'<div class="empty">No purchased courses yet.<br><button class="primary" style="margin-top:12px" onclick="go(\'courses\')">Find a Course</button></div>'}</div></section>`}
function renderCourses(){const cs=DB.courses||[];$('content').innerHTML=`<div class="page-head"><div><div class="eyebrow">ACADEMY CATALOG</div><h1>Explore Courses</h1><p>Choose a course, submit your details and pay securely through the academy QR.</p></div><input class="search" id="courseSearch" placeholder="Search courses…" oninput="filterCourses()"></div><div id="courseGrid" class="course-grid">${cs.map(courseCard).join('')}</div>`}
function courseCard(c){const own=active(c.id),expired=enrollment(c.id)&&!own;return `<article class="course-card reveal"><div class="course-img" style="background-image:url('${c.image||'/shahid.jpg'}')"><span>${c.category}</span>${expired?'<em class="expired">Expired</em>':''}</div><div class="course-body"><h3>${c.title}</h3><div class="small">${c.startDate?'Starts: '+new Date(c.startDate).toLocaleDateString('en-IN'):'Start date not announced'}</div><p>${c.description}</p><div class="meta"><span>★ 4.9</span><span>${c.level}</span><span>${c.duration}</span></div><div class="price"><b>${money(c.price)}</b><s>${money(c.oldPrice)}</s></div><div class="row">${own?`<button type="button" class="primary" data-open-course="${esc(c.id)}">Open Course</button>`:`<button class="outline" onclick="viewCourse('${c.id}')">View</button><button class="primary" onclick="startPurchase('${c.id}')">Buy Now</button>`}</div></div></article>`}
function filterCourses(){const q=$('courseSearch').value.toLowerCase();$('courseGrid').innerHTML=DB.courses.filter(c=>(c.title+c.category+c.description).toLowerCase().includes(q)).map(courseCard).join('')}
function viewCourse(id){const c=course(id);openModal(`<div class="eyebrow">${c.category.toUpperCase()}</div><h2>${c.title}</h2><p>${c.description}</p><div class="info-grid"><div class="info"><small>Duration</small><b>${c.duration}</b></div><div class="info"><small>Level</small><b>${c.level}</b></div><div class="info"><small>Lessons</small><b>${c.lessons.length}</b></div><div class="info"><small>Price</small><b>${money(c.price)}</b></div></div><div class="locked"><b>Course access is unlocked after payment verification.</b><br><small>After you pay, upload the real payment screenshot and wait for academy approval.</small></div><button class="primary wide" onclick="startPurchase('${id}')">Continue to Purchase</button>`)}
function startPurchase(id){if(!current)return;const c=course(id);openModal(`<div class="eyebrow">STEP 1 OF 2 • STUDENT DETAILS</div><h2>Join ${c.title}</h2><p>Fill your current details. These details will reach the academy with your payment request.</p><form class="form" onsubmit="submitApplication(event,'${id}')"><label>Full name</label><input id="fn" value="${current.name==='New Student'?'':current.name||''}" required><label>Country</label><select id="ac"><option value="+91">India +91</option><option value="+92">Pakistan +92</option><option value="+1">USA/Canada +1</option><option value="+44">UK +44</option><option value="+971">UAE +971</option></select><label>Current 10-digit mobile number</label><input id="ph" value="${(current.phone||'').replace(/^\+\d+/,'')}" inputmode="numeric" maxlength="10" required><label>Email for academy notifications</label><input id="em" type="email" value="${current.email||''}" required placeholder="you@example.com"><label>Address</label><input id="addr" placeholder="Village / locality / full address"><label>City / District</label><input id="city"><label>Qualification / class</label><input id="qual"><label>Profile photo</label><input id="pf" type="file" accept="image/*"><button class="primary">Continue to Payment →</button></form>`)}
async function submitApplication(e,id){e.preventDefault();const fd=new FormData();fd.append('courseId',id);fd.append('fullName',$('fn').value);fd.append('country',$('ac').value);fd.append('email',$('em').value);fd.append('address',$('addr').value);fd.append('city',$('city').value);fd.append('qualification',$('qual').value);if($('pf').files[0])fd.append('profile',$('pf').files[0]);try{const j=await api('/api/application',{method:'POST',body:fd});current.name=j.application.fullName;current.email=j.application.email;localStorage.setItem('hsa_user',JSON.stringify(current));openPayment(id,j.application.id)}catch(err){toast(err.message)}}
function openPayment(id,applicationId){const c=course(id);const settings=DB?.settings&&typeof DB.settings==='object'?DB.settings:{};openModal(`<div class="eyebrow">STEP 2 OF 2 • PAYMENT</div><h2>Scan & Pay</h2><p><b>${c.title}</b> — <strong>${money(c.price)}</strong></p><div class="qr-wrap"><img src="/payment-qr.jpg" alt="Academy UPI QR"><b>UPI ID</b><div>${settings.upiId||'Academy UPI ID'}</div></div><div class="timer" id="payTimer">20:00</div><div class="notice">The QR payment window stays open for <b>20 minutes</b>. Pay from your own UPI app, then upload the actual screenshot and UTR. <b>Access is never unlocked from the screenshot alone.</b></div><form class="form" onsubmit="submitPayment(event,'${id}')"><label>UPI transaction reference / UTR</label><input id="utr" placeholder="Enter UTR / transaction ID"><label>Real payment screenshot</label><input id="shot" type="file" accept="image/*" required><button class="primary">Submit for Verification</button></form>`);startTimer(1200)}
function startTimer(sec){clearInterval(timer);timer=setInterval(()=>{sec--;const e=$('payTimer');if(e)e.textContent=`${String(Math.floor(sec/60)).padStart(2,'0')}:${String(sec%60).padStart(2,'0')}`;if(sec<=0){clearInterval(timer);toast('Payment window expired. Start again if needed.')}},1000)}
async function submitPayment(e,id){e.preventDefault();const fd=new FormData();fd.append('courseId',id);fd.append('utr',$('utr').value);fd.append('screenshot',$('shot').files[0]);try{await api('/api/payment',{method:'POST',body:fd});closeModal();toast('Payment submitted. We will verify the money and unlock your course.');await loadStudent();go('purchased')}catch(err){toast(err.message)}}
function openCourse(id){try{id=decodeURIComponent(String(id))}catch{}const c0=course(id);if(!c0){toast('Course could not be found. Please refresh the student page.');return false}if(!active(id)){const e=enrollment(id);toast(e?'This course access has expired.':'Please purchase the course first.');return false}try{sessionStorage.setItem('hsa_student_page','course');sessionStorage.setItem('hsa_course_id',String(id));sessionStorage.removeItem('hsa_lesson_id')}catch{}const c=course(id),e=enrollment(id)||{endDate:'2099-12-31T23:59:59.000Z'},lessons=c.lessons||[],done=current?.completedLessons?.[id]||[];$('content').innerHTML=`<div class="page-head"><div><div class="eyebrow">COURSE WORKSPACE</div><h1>${esc(c.title)}</h1><p>Course start: ${c.startDate?new Date(c.startDate).toLocaleDateString('en-IN'):'Available now'} • Access ends ${new Date(e.endDate).toLocaleDateString('en-IN')}</p></div><button class="outline" onclick="go('purchased')">Back</button></div><div class="course-progress-card card"><div><span class="eyebrow">YOUR PROGRESS</span><h3>${progress(id)}% Complete</h3><p>${done.length}/${lessons.length||0} lessons completed • Certificate unlocks at 80%</p></div><div class="progress big-progress"><i style="width:${progress(id)}%"></i></div></div><div class="course-shell"><aside class="card course-outline"><b>Recorded Classes</b><small>${lessons.length} lessons</small><div id="lessonList">${lessons.map((l,i)=>`<button class="lesson-nav ${done.includes(l.id)?'completed':''}" onclick="watchLesson('${id}','${l.id}')"><span>${done.includes(l.id)?'✓':i+1}</span>${esc(l.title)}</button>`).join('')||'<div class="empty">No lessons uploaded yet.</div>'}</div></aside><section><div class="player-placeholder locked"><h3>Select a lesson</h3><p>Choose a recorded class from the list.</p></div><div class="course-tabs"><button onclick="renderCourseMaterials('${id}')">Study Material</button><button onclick="renderCourseAssignments('${id}')">Assignments</button><button onclick="renderCourseLive('${id}')">Live Classes</button><button type="button" onclick="renderCourseDoubts('${id}')">Ask Doubt</button></div><div id="courseSub"></div></section></div>`;return true;}
function videoPoster(l){if(l?.thumbnail)return l.thumbnail;try{const u=new URL(l?.video||'');if(u.hostname.includes('youtube.com')||u.hostname.includes('youtu.be')){const id=u.hostname.includes('youtu.be')?u.pathname.split('/').filter(Boolean)[0]:u.searchParams.get('v')||u.pathname.match(/\/(?:shorts|embed|live)\/([^/?]+)/)?.[1];if(id)return `https://img.youtube.com/vi/${id}/hqdefault.jpg`;}}catch{}return '';}
function watchLesson(cid,lid){const c=course(cid),l=c?.lessons?.find(x=>x.id===lid);if(!l)return;try{sessionStorage.setItem('hsa_student_page','course');sessionStorage.setItem('hsa_course_id',String(cid));sessionStorage.setItem('hsa_lesson_id',String(lid))}catch{}let media='';const poster=videoPoster(l);if(l.type==='upload')media=`<div class="video-frame">${poster?`<video controls playsinline preload="metadata" controlsList="nodownload" poster="${poster}" src="${l.video}"></video>`:`<video controls playsinline preload="metadata" controlsList="nodownload" src="${l.video}"></video>`}</div>`;else{const embed=youtubeEmbed(l.video);media=embed?`<div class="video-frame"><iframe src="${embed}" title="${esc(l.title)}" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe></div>`:`<div class="locked"><b>Video link could not be opened.</b><p>Please ask the academy to check this YouTube link.</p></div>`;}$('content').querySelector('.player-placeholder').outerHTML=`<div class="player"><div class="player-kicker">LESSON ${((c.lessons||[]).findIndex(x=>x.id===lid)+1)} OF ${(c.lessons||[]).length}</div>${media}<div class="player-body"><b>${esc(l.title)}</b><p>${esc(l.description||'')}</p><span class="class-type-pill">${l.type==='upload'?'Recorded video':'YouTube class'}</span></div></div>`;$('content').querySelector('.course-tabs').insertAdjacentHTML('afterend',`<div class="lesson-actions row" style="margin-top:14px"><button class="primary" onclick="completeLesson('${cid}','${lid}')">${(current?.completedLessons?.[cid]||[]).includes(lid)?'✓ Lesson Completed':'Mark Lesson Complete'}</button><button type="button" class="outline" onclick="openDoubtForm('${cid}','${lid}')">Ask a Doubt</button></div><div class="card lesson-comments" id="lessonComments">${renderLessonComments(cid,lid)}</div>`);}
function renderLessonComments(cid,lid){const arr=(DB.comments||[]).filter(x=>x.courseId===cid&&x.lessonId===lid).slice(0,20);return `<div class="section-title-row"><div><h3>Discussion</h3><p class="small">Ask, discuss and learn together.</p></div></div><form class="comment-form" onsubmit="addComment(event,'${cid}','${lid}')"><input id="commentText" placeholder="Write a respectful comment…" required><button class="primary">Post</button></form><div class="comment-list">${arr.map(x=>`<article class="comment-item"><div class="avatar">${esc((x.studentName||'S').slice(0,2).toUpperCase())}</div><div><b>${esc(x.studentName||'Student')}</b><p>${esc(x.text)}</p><small>${new Date(x.createdAt).toLocaleString('en-IN')}</small></div></article>`).join('')||'<div class="empty">No comments yet. Be the first to start the discussion.</div>'}</div>`}
async function addComment(e,cid,lid){e.preventDefault();const text=$('commentText').value.trim();if(!text)return;try{await api('/api/comment',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({courseId:cid,lessonId:lid,text})});await loadStudent();watchLesson(cid,lid);toast('Comment posted.')}catch(err){toast(err.message)}}
async function completeLesson(cid,lid){try{const r=await api('/api/progress',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({courseId:cid,lessonId:lid})});await loadStudent();toast(r.progress>=80?'80% reached — certificate unlocked!':`Progress updated to ${r.progress}%`);openCourse(cid);setTimeout(()=>watchLesson(cid,lid),0)}catch(err){toast(err.message)}}
function renderCourseMaterials(cid){$('courseSub').innerHTML=(DB.materials||[]).filter(m=>m.courseId===cid).map(m=>`<div class="material-item"><div><b>${m.title}</b><div class="small">${m.originalName}</div></div><a class="primary" href="${m.file}" download>Download</a></div>`).join('')||'<div class="empty">No material uploaded yet.</div>'}
function renderCourseAssignments(cid){const arr=(DB.assignments||[]).filter(a=>a.courseId===cid);$('courseSub').innerHTML=arr.map(a=>{const s=DB.submissions.find(x=>x.assignmentId===a.id);return `<div class="assignment-item"><div><span class="badge">${a.points} points</span><h3>${a.title}</h3><p>${a.description}</p><small>Due: ${a.dueDate||'No date'} ${s?`• ${s.status} ${s.score!==null?'• '+s.score+'/'+a.points:''}`:''}</small></div><button class="primary" onclick="submitAssignment('${a.id}')">${s?'Update':'Submit'}</button></div>`}).join('')||'<div class="empty">No assignments yet.</div>'}
function renderCourseLive(cid){const arr=(DB.liveClasses||[]).filter(l=>l.courseId===cid).sort((a,b)=>new Date(`${a.date}T${a.time||'00:00'}`)-new Date(`${b.date}T${b.time||'00:00'}`));$('courseSub').innerHTML=arr.map(l=>`<article class="class-event-card"><div class="class-event-date"><b>${new Date(l.date).getDate()}</b><span>${new Date(l.date).toLocaleString('en',{month:'short'})}</span></div><div class="class-event-main"><span class="class-type-pill">LIVE CLASS</span><h3>${l.title}</h3><p>${new Date(`${l.date}T${l.time||'00:00'}`).toLocaleDateString('en-IN',{weekday:'long',day:'numeric',month:'long',year:'numeric'})} • ${l.time}</p></div><a class="primary" href="${l.zoom}" target="_blank" rel="noopener">Join Zoom</a></article>`).join('')||'<div class="empty">No live class scheduled.</div>'}
function renderMaterials(){const arr=DB.materials||[];$('content').innerHTML=`<div class="page-head"><div><div class="eyebrow">RESOURCES</div><h1>Study Material</h1></div></div><div class="material-list">${arr.map(m=>`<div class="material-item"><div><span class="badge">${course(m.courseId)?.title||''}</span><h3>${m.title}</h3><small>${m.originalName}</small></div><a class="primary" href="${m.file}" download>Download</a></div>`).join('')||'<div class="empty">No study material for your active courses.</div>'}</div>`}
function renderDownloads(){renderMaterials()}
function renderAssignments(){const arr=DB.assignments||[];$('content').innerHTML=`<div class="page-head"><div><div class="eyebrow">PRACTICE</div><h1>Assignments</h1></div></div><div class="assignment-list">${arr.map(a=>{const s=DB.submissions.find(x=>x.assignmentId===a.id);return `<div class="assignment-item"><div><span class="badge">${course(a.courseId)?.title||''}</span><h3>${a.title}</h3><p>${a.description}</p><small>Due: ${a.dueDate||'No date'} ${s?`• ${s.status}`:''}</small></div><button class="primary" onclick="submitAssignment('${a.id}')">${s?'Update':'Submit'}</button></div>`}).join('')||'<div class="empty">No assignments available.</div>'}</div>`}
function submitAssignment(id){const a=DB.assignments.find(x=>x.id===id),s=DB.submissions.find(x=>x.assignmentId===id);openModal(`<div class="eyebrow">ASSIGNMENT</div><h2>${a.title}</h2><p>${a.description}</p><form class="form" onsubmit="sendAssignment(event,'${id}')"><label>Your answer</label><textarea id="ans" rows="8" required>${s?.answer||''}</textarea><label>File (optional)</label><input id="afile" type="file"><button class="primary">Submit Assignment</button></form>`)}
async function sendAssignment(e,id){e.preventDefault();const fd=new FormData();fd.append('assignmentId',id);fd.append('answer',$('ans').value);if($('afile').files[0])fd.append('file',$('afile').files[0]);try{await api('/api/assignment/submit',{method:'POST',body:fd});closeModal();await loadStudent();renderAssignments();toast('Assignment submitted!')}catch(err){toast(err.message)}}
function renderLive(){const arr=(DB.liveClasses||[]).filter(l=>active(l.courseId)).sort((a,b)=>new Date(`${a.date}T${a.time||'00:00'}`)-new Date(`${b.date}T${b.time||'00:00'}`));$('content').innerHTML=`<div class="page-head"><div><div class="eyebrow">LIVE LEARNING</div><h1>Weekly Schedule</h1><p>Upcoming live classes and Zoom sessions for your purchased courses.</p></div></div><div class="schedule-head"><span>UPCOMING EVENTS</span><b>${arr.length}</b></div><div class="class-event-list">${arr.map(l=>`<article class="class-event-card"><div class="class-event-date"><b>${new Date(l.date).getDate()}</b><span>${new Date(l.date).toLocaleString('en',{month:'short'})}</span></div><div class="class-event-main"><span class="badge">${course(l.courseId)?.title||'Course'}</span><h3>${l.title}</h3><p>${new Date(`${l.date}T${l.time||'00:00'}`).toLocaleDateString('en-IN',{weekday:'long',day:'numeric',month:'long',year:'numeric'})} • ${l.time}</p><small>Online • Zoom</small></div><a class="primary" href="${l.zoom}" target="_blank" rel="noopener">Join Class</a></article>`).join('')||'<div class="empty">No live classes scheduled for your active courses.</div>'}</div>`}
async function renderCertificates(){const j=await api('/api/certificates');$('content').innerHTML=`<div class="page-head"><div><div class="eyebrow">ACHIEVEMENT</div><h1>My Certificate</h1><p>Certificates unlock automatically at 80% course completion.</p></div></div>${j.certificates.map(c=>`<div class="certificate card"><div class="cert-badge"><img src="/academy-logo.png" alt="Hafiz Shahid Academy logo"></div><div><div class="eyebrow">CERTIFICATE OF COMPLETION</div><h2>${c.courseTitle}</h2><p>This certifies that <b>${c.studentName}</b> completed at least 80% of the course.</p><div class="small">Certificate No: ${c.certificateNo} • Issued: ${new Date(c.issuedAt).toLocaleDateString('en-IN')}</div></div><button class="primary" onclick="printCertificate(${JSON.stringify(c).replace(/"/g,'&quot;')})">Print</button></div>`).join('')||'<div class="empty">Reach 80% progress to unlock your certificate.</div>'}`}
function printCertificate(c){const w=window.open('','_blank');w.document.write(`<html><head><title>${c.certificateNo}</title><style>body{font-family:Georgia;background:#f4f7fb;padding:40px}.box{background:#fff;border:12px solid #0a1b35;padding:70px;text-align:center;max-width:850px;margin:auto}.gold{color:#c9981b}h1{font-size:42px}</style></head><body><div class="box"><div class="gold">HAFIZ SHAHID'S ACADEMY</div><h1>Certificate of Completion</h1><p>This certificate is proudly presented to</p><h2>${c.studentName}</h2><p>for completing at least 80% of</p><h2 class="gold">${c.courseTitle}</h2><p>Certificate No. ${c.certificateNo}</p><button onclick="window.print()">Print / Save PDF</button></div></body></html>`);w.document.close()}
function renderProfile(){const e=(current.enrollments||[]);$('content').innerHTML=`<div class="page-head"><div><div class="eyebrow">MY ACCOUNT</div><h1>About Me</h1><p>Your verified student identity and learning details.</p></div></div><div class="profile"><div class="card profile-side"><img src="${current.profilePhoto||'/shahid.jpg'}"><h3>${current.name}</h3><div class="badge">Verified phone ${current.phone}</div></div><div class="card"><h3>Profile details</h3><form class="form" onsubmit="saveProfile(event)"><label>Full name</label><input id="pn" value="${current.name||''}" required><label>Email</label><input id="pe" type="email" value="${current.email||''}"><label>Country</label><select id="pc"><option value="+91">India +91</option><option value="+92">Pakistan +92</option><option value="+1">USA/Canada +1</option><option value="+44">UK +44</option></select><label>Verified mobile number</label><input id="pp" value="${current.phone||''}" readonly><label>About me</label><textarea id="pa">${current.about||''}</textarea><label>Profile photo</label><input id="pph" type="file" accept="image/*"><button class="primary">Save Profile</button></form></div></div>`}
async function saveProfile(e){e.preventDefault();const fd=new FormData();fd.append('name',$('pn').value);fd.append('email',$('pe').value);fd.append('country',$('pc').value);fd.append('phone',$('pp').value);fd.append('about',$('pa').value);if($('pph').files[0])fd.append('profile',$('pph').files[0]);try{const j=await api('/api/auth/profile',{method:'POST',body:fd});current=j.user;await loadStudent();toast('Profile updated');renderProfile()}catch(err){toast(err.message)}}
function renderSettings(){$('content').innerHTML=`<div class="page-head"><div><div class="eyebrow">ACCOUNT</div><h1>Settings</h1><p>Simple controls for your demo account.</p></div></div><div class="card"><h3>Security</h3><p class="small">Your Student ID and password protect your account. Keep your login details private and sign out on shared devices.</p><button class="outline" onclick="logout()">Sign out this device</button></div>`}
function renderNotifications(){const arr=DB.notifications||[];$('content').innerHTML=`<div class="page-head"><div><div class="eyebrow">UPDATES</div><h1>Notifications</h1><p>Academy announcements, classes, assignments and account updates.</p></div></div><div class="notification-list">${arr.map(n=>{const read=(Array.isArray(n.readBy)&&n.readBy.includes(current.id))||n.read;return `<button class="notification-item ${read?'read':''}" onclick="readNotification('${n.id}')"><span class="notif-icon">${n.type==='certificate'?'🏆':n.type==='payment'?'💳':n.type==='doubt'?'❓':'🔔'}</span><span><b>${esc(n.title)}</b><p>${esc(n.text)}</p><small>${new Date(n.createdAt).toLocaleString('en-IN')}${read?' • Read':' • New'}</small></span></button>`}).join('')||'<div class="empty">No notifications.</div>'}</div>`}
async function readNotification(id){try{await api('/api/notification/'+id+'/read',{method:'POST'});const n=DB.notifications.find(x=>x.id===id);if(n)n.read=true;renderHeader();renderNotifications()}catch(err){toast(err.message)}}
function renderDoubts(){const arr=DB.doubts||[];$('content').innerHTML=`<div class="page-head"><div><div class="eyebrow">STUDENT SUPPORT</div><h1>My Doubts</h1><p>Ask the academy whenever you are stuck.</p></div><button class="primary" onclick="openDoubtForm()">Ask a Doubt →</button></div><div class="doubt-list">${arr.map(x=>`<article class="doubt-card card"><div class="doubt-top"><span class="class-type-pill ${x.status==='Answered'?'answered':''}">${x.status}</span><small>${new Date(x.createdAt).toLocaleString('en-IN')}</small></div><h3>${esc(x.subject||course(x.courseId)?.title||'Academy Doubt')}</h3><p>${esc(x.message)}</p>${x.reply?`<div class="doubt-reply"><b>Academy Reply</b><p>${esc(x.reply)}</p><small>${x.repliedAt?new Date(x.repliedAt).toLocaleString('en-IN'):''}</small></div>`:'<div class="small">Waiting for academy reply…</div>'}</article>`).join('')||'<div class="empty">No doubts yet.</div>'}</div>`}
function openDoubtForm(courseId='',lessonId=''){if(!$('modal')||!$('modalBody')){toast('Doubt form could not open. Please refresh the student page.');return}const cid=String(courseId||'');const lid=String(lessonId||'');const options=(DB.courses||[]).filter(c=>active(c.id)).map(c=>`<option value="${esc(c.id)}" ${String(c.id)===cid?'selected':''}>${esc(c.title)}</option>`).join('');openModal(`<div class="eyebrow">STUDENT SUPPORT</div><h2>Ask a Doubt</h2><p>Send your question to the academy. You can include the course and lesson for faster help.</p><form class="form" onsubmit="sendDoubt(event)"><label>Course</label><select id="dCourse"><option value="">General Academy Question</option>${options}</select><label>Subject</label><input id="dSubject" value="${lid?'Lesson question':''}" placeholder="Subject"><label>Your doubt</label><textarea id="dMessage" rows="7" placeholder="Describe your doubt clearly…" required></textarea><input id="dLesson" type="hidden" value="${esc(lid)}"><button type="submit" class="primary">Send Doubt</button></form>`);setTimeout(()=>$('dMessage')?.focus(),50)}
async function sendDoubt(e){e.preventDefault();const message=String($('dMessage')?.value||'').trim();if(!message){toast('Please write your doubt first.');return}try{await api('/api/doubt',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({courseId:$('dCourse')?.value||'',lessonId:$('dLesson')?.value||'',subject:$('dSubject')?.value||'',message})});closeModal();await loadStudent();go('doubts');toast('Doubt sent to the academy.')}catch(err){toast(err.message)}}
function renderCourseDoubts(cid='',lid=''){if(cid){openDoubtForm(cid,lid);return}go('doubts')}
function renderGlobalSearch(){const q=(DB.searchQuery||'').trim().toLowerCase(),courses=(DB.courses||[]).filter(c=>active(c.id)),lessons=courses.flatMap(c=>(c.lessons||[]).map(l=>({...l,courseId:c.id}))).filter(l=>(l.title+' '+(l.description||'')).toLowerCase().includes(q));$('content').innerHTML=`<div class="page-head"><div><div class="eyebrow">ACADEMY SEARCH</div><h1>Search Academy</h1><p>Find your courses, recorded classes and study resources.</p></div><input class="search global-search-input" value="${esc(DB.searchQuery||'')}" placeholder="Search courses, lessons…" oninput="DB.searchQuery=this.value;renderGlobalSearch()"></div><div class="search-results"><h3>Courses</h3>${courses.filter(c=>(c.title+' '+c.category+' '+c.description).toLowerCase().includes(q)).map(c=>`<button class="search-result-card" onclick="active('${c.id}')&&openCourse('${c.id}')"><span class="search-result-icon">▣</span><span><b>${esc(c.title)}</b><small>${esc(c.category)} • ${c.lessons.length} lessons</small></span></button>`).join('')||'<div class="empty">No matching courses.</div>'}<h3 style="margin-top:24px">Recorded Classes</h3>${lessons.map(l=>`<button class="search-result-card" onclick="openCourse('${l.courseId}');setTimeout(()=>watchLesson('${l.courseId}','${l.id}'),0)"><span class="search-result-icon">▶</span><span><b>${esc(l.title)}</b><small>${esc(course(l.courseId)?.title||'Course')}</small></span></button>`).join('')||'<div class="empty">No matching lessons.</div>'}</div>`}

async function boot(){
  try{
    await loadPublic();
    applyBranding();
    hideLastStudentSuggestion();
    const q=new URLSearchParams(location.search),preview=q.get('adminPreview');
    if(preview){
      const r=await fetch('/api/auth/student-preview?token='+encodeURIComponent(preview),{cache:'no-store'});const j=await r.json();if(!r.ok)throw Error(j.error||'Preview expired');
      studentToken=j.token;current=j.user;
      try{sessionStorage.setItem('hsa_preview_student_token',studentToken);sessionStorage.setItem('hsa_preview_student','1')}catch{}
      const previewCourse=q.get('previewCourse')||'';try{sessionStorage.setItem('hsa_preview_course',previewCourse)}catch{}
      history.replaceState({},'',location.pathname);await loadStudent();
      $('publicHome').classList.add('hidden');$('loginOverlay').classList.add('hidden');$('app').classList.remove('hidden');
      if(previewCourse&&active(previewCourse)){openCourse(previewCourse)}else go('home');return;
    }
    const previewStudentToken=sessionStorage.getItem('hsa_preview_student_token')||'';
    if(previewStudentToken){
      studentToken=previewStudentToken;
      try{
        await loadStudent();
        $('publicHome').classList.add('hidden');$('loginOverlay').classList.add('hidden');$('app').classList.remove('hidden');
        const cid=sessionStorage.getItem('hsa_preview_course')||sessionStorage.getItem('hsa_course_id')||'';
        if(cid&&active(cid))openCourse(cid);else{const page=sessionStorage.getItem('hsa_student_page')||'home';go(page==='course'?'home':page);}
        return;
      }catch(err){console.warn('Student preview session could not be restored:',err);sessionStorage.removeItem('hsa_preview_student_token');sessionStorage.removeItem('hsa_preview_student');sessionStorage.removeItem('hsa_preview_course');studentToken='';}
    }
    const savedToken=localStorage.getItem('hsa_student_token');
    if(savedToken){
      studentToken=savedToken;
      try{
        await loadStudent();
        $('publicHome').classList.add('hidden');$('loginOverlay').classList.add('hidden');$('app').classList.remove('hidden');
        const page=sessionStorage.getItem('hsa_student_page')||'home';
        if(page==='course'){
          const cid=sessionStorage.getItem('hsa_course_id')||'';const lid=sessionStorage.getItem('hsa_lesson_id')||'';
          if(cid&&openCourse(cid)&&lid)setTimeout(()=>watchLesson(cid,lid),0);else go('home');
        }else go(page);
        return;
      }catch(err){
        console.warn('Saved student session could not be restored:',err);
        studentToken='';localStorage.removeItem('hsa_student_token');localStorage.removeItem('hsa_user');
      }
    }
    $('publicHome').classList.remove('hidden');$('app').classList.add('hidden');
    const keepLogin=location.hash==='#login'||sessionStorage.getItem('hsa_login_open')==='1';
    if(keepLogin){$('loginOverlay').classList.remove('hidden');document.body.classList.add('login-open');setTimeout(()=>$('studentEmail')?.focus(),100)}else $('loginOverlay').classList.add('hidden');
  }catch(err){console.error(err);toast('Academy could not load. Please refresh.');}
}
// Delegated course-opening handler: works even when course cards are re-rendered dynamically.
document.addEventListener('click',e=>{const b=e.target.closest('[data-open-course]');if(!b)return;e.preventDefault();e.stopPropagation();openCourse(b.getAttribute('data-open-course')||'');});
boot();
